// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"FixClassChangeSkill","status":true,"description":"職業の変更によるスキル習得プラグイン","parameters":{"invalidSwitchId":"0"}},
{"name":"TMEventItemEx","status":true,"description":"アイテム選択の処理にヘルプウィンドウを追加し、\n個数表示の有無と表示行数をアイテムタイプごとに設定できます。","parameters":{"helpWindowEnabledItem":"1","helpWindowEnabledKey":"1","helpWindowEnabledA":"1","helpWindowEnabledB":"1","showItemNumberItem":"1","showItemNumberKey":"1","showItemNumberA":"1","showItemNumberB":"1","numVisibleRowsItem":"4","numVisibleRowsKey":"4","numVisibleRowsA":"4","numVisibleRowsB":"4","fixPlacement":"top"}},
{"name":"ChoiceActors","status":true,"description":"アクター選択肢作成プラグイン","parameters":{"AChoiceVariableNumber":"1","CancelChoiceMessage":"キャンセル"}}
];
